version: '3.3'

services:

    # Nuxt
    nuxt:
        build:
            context: ./
            dockerfile: ./.config/docker/node/nuxt_${NODE_VERSION}.Dockerfile
            target: ${APP_ENV}
            args:
                node_root_dir: ${NODE_ROOT_DIR}
                nuxt_root_dir: ${NUXT_ROOT_DIR}
                npm_version: ${NPM_VERSION}
                pnpm_version: ${PNPM_VERSION}
        container_name: ${NUXT_HOST}
        restart: unless-stopped
        expose:
            - "${NUXT_PORT:-3000}"
        environment:
            APP_NAME: ${APP_NAME}
            APP_URL: ${APP_URL}
            NODE_ENV: ${APP_ENV}
            NUXT_HOST: ${NUXT_HOST}
            NUXT_PORT: ${NUXT_PORT:-3000}
            MONGO_HOST: ${MONGO_HOST}
            MONGO_PORT: ${MONGO_PORT:-27017}
            EDITOR: nano
        working_dir: ${NUXT_ROOT_DIR}
        volumes:
            - ./.logs/nuxt:${NUXT_LOG_DIR}
            - ./nuxt:${NUXT_ROOT_DIR}
        command: [ "tail", "-f", "/dev/null" ]
        networks:
            - db
            - web
    
    # Database
    mongo:
        build:
            context: ./
            dockerfile: ./.config/docker/mongo/mongo_${MONGO_VERSION}.Dockerfile
            target: ${APP_ENV}
            args:
                app_env: ${APP_ENV}
                mongo_host: ${MONGO_HOST}
                mongo_port: ${MONGO_PORT:-27017}
                mongo_root_dir: ${MONGO_ROOT_DIR}
                mongo_log_dir: ${MONGO_LOG_DIR}
                mongo_root_username: ${MONGO_ROOT_USERNAME}
                mongo_root_password: ${MONGO_ROOT_PASSWORD}
        container_name: ${MONGO_HOST}
        restart: unless-stopped
        expose:
            - "${MONGO_PORT:-27017}"
        environment:
            EDITOR: nano
        working_dir: ${MONGO_ROOT_DIR}
        volumes:
            - ./.logs/mongo:${MONGO_LOG_DIR}
            - ./mongo:${MONGO_ROOT_DIR}
        networks:
            - db

    # Database Explorer
    mongo-express:
        image: mongo-express:${ME_VERSION}
        container_name: ${ME_HOST}
        restart: unless-stopped
        expose:
            - "${ME_PORT:-8081}"
        depends_on:
            - mongo
        environment:
            PORT: ${ME_PORT:-8081}
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_PORT: ${MONGO_PORT:-27017}
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
            ME_CONFIG_BASICAUTH: ${ME_CONFIG_BASICAUTH}
            ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
            ME_CONFIG_SITE_BASEURL: ${ME_CONFIG_SITE_BASEURL}
            ME_CONFIG_SITE_COOKIESECRET: ${ME_CONFIG_SITE_COOKIESECRET}
            ME_CONFIG_SITE_SESSIONSECRET: ${ME_CONFIG_SITE_SESSIONSECRET}
        networks:
            - db
            - web

    # Webserver
    nginx:
        image: nginx:${WEB_VERSION}
        container_name: ${WEB_HOST}
        restart: always
        ports:
            - "${WEB_PORT:-80}:${WEB_PORT:-80}"
            - "${WEB_SSL_PORT:-443}:${WEB_SSL_PORT:-443}"
        depends_on:
            - nuxt
            - mongo-express
        environment:
            APP_ENV: ${APP_ENV}
            APP_DOMAIN: ${APP_DOMAIN}
            NUXT_HOST: ${NUXT_HOST}
            NUXT_PORT: ${NUXT_PORT:-3000}
            ME_HOST: ${ME_HOST}
            ME_PORT: ${ME_PORT:-8081}
            ME_CONFIG_SITE_BASEURL: ${ME_CONFIG_SITE_BASEURL}
            WEB_PORT: ${WEB_PORT:-80}
            WEB_SSL_PORT: ${WEB_SSL_PORT:-443}
            WEB_ROOT_DIR: ${WEB_ROOT_DIR}
            WEB_LOG_DIR: ${WEB_LOG_DIR}
            WEB_LOG_LEVEL: ${WEB_LOG_LEVEL}
        working_dir: ${WEB_ROOT_DIR}
        volumes:
            - ./.config/nginx/${APP_ENV}.conf.template:/etc/nginx/templates/default.conf.template:ro
            - ./.logs/nginx:${WEB_LOG_DIR}
        networks:
            - web

networks:
    db:
        driver: bridge
    web:
        driver: bridge

volumes:
    mongo_data:
