# See: https://github.com/alvarosabu/pnpm-monorepo-nuxt/blob/main/netlify.toml
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version" # prevent Netlify npm install
[build]
  publish = "./.output"
  command = "npx npm i --store=node_modules --frozen-lockfile && npx npm run generate:ci"
[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
